services:
  db:
    container_name: db
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

volumes:
  db_data: